### ISSUE TITLE
 openwrt-a1300

### ISSUE THREAD

**Issue by lexcomeing** [zheshifandian/openwrt-a1300#1]
ubuntu20.04

In file included from drivers/mtd/nand/spi/gigadevice.c:9:
drivers/mtd/nand/spi/gigadevice.c:244:10: error: 'gd5fxgq5xexxg_ecc_get_status' undeclared here (not in a function); did you mean 'gd5fxgq4uexxg_ecc_get_status'?
          gd5fxgq5xexxg_ecc_get_status)),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/mtd/spinand.h:334:3: note: in definition of macro 'SPINAND_INFO'
   __VA_ARGS__      \
   ^~~~~~~~~~~
drivers/mtd/nand/spi/gigadevice.c:243:8: note: in expansion of macro 'SPINAND_ECCINFO'
        SPINAND_ECCINFO(&gd5fxgq4_variant2_ooblayout,
        ^~~~~~~~~~~~~~~
make[9]: *** [scripts/Makefile.build:262: drivers/mtd/nand/spi/gigadevice.o] Error 1
make[8]: *** [scripts/Makefile.build:497: drivers/mtd/nand/spi] Error 2
make[7]: *** [scripts/Makefile.build:497: drivers/mtd/nand] Error 2
make[6]: *** [scripts/Makefile.build:497: drivers/mtd] Error 2
make[5]: *** [Makefile:1734: drivers] Error 2

**Comment by zheshifandian** [comment]
先使用5.10内核编译
